adj_dekl(masc, nom, mixed_type, "er").
adj_dekl(neu, nom, mixed_type, "es").
adj_dekl(fem, nom, mixed_type, "e").
adj_dekl(masc, gen, mixed_type, "en").
adj_dekl(neu, gen, mixed_type, "en").
adj_dekl(fem, gen, mixed_type, "en").
adj_dekl(masc, dat, mixed_type, "en").
adj_dekl(neu, dat, mixed_type, "en").
adj_dekl(fem, dat, mixed_type, "en").
adj_dekl(masc, akk, mixed_type, "en").
adj_dekl(neu, akk, mixed_type, "es").
adj_dekl(fem, akk, mixed_type, "e").

adj_dekl(masc, nom, strong_type, "er").
adj_dekl(neu, nom, strong_type, "es").
adj_dekl(fem, nom, strong_type, "e").
adj_dekl(masc, gen, strong_type, "en").
adj_dekl(neu, gen, strong_type, "er").
adj_dekl(fem, gen, strong_type, "en").
adj_dekl(masc, dat, strong_type, "em").
adj_dekl(neu, dat, strong_type, "em").
adj_dekl(fem, dat, strong_type, "er").
adj_dekl(masc, akk, strong_type, "en").
adj_dekl(neu, akk, strong_type, "es").
adj_dekl(fem, akk, strong_type, "e").

adj_dekl(masc, nom, weak_type, "e").
adj_dekl(neu, nom, weak_type, "e").
adj_dekl(fem, nom, weak_type, "e").
adj_dekl(masc, gen, weak_type, "en").
adj_dekl(neu, gen, weak_type, "en").
adj_dekl(fem, gen, weak_type, "en").
adj_dekl(masc, dat, weak_type, "en").
adj_dekl(neu, dat, weak_type, "en").
adj_dekl(fem, dat, weak_type, "en").
adj_dekl(masc, akk, weak_type, "en").
adj_dekl(neu, akk, weak_type, "e").
adj_dekl(fem, akk, weak_type, "e").